
<?php
$title="Epic Game Play Trade - Terms Of Service";
require 'includes\part\header.php';

?>
<div class="container bg-white">
<h2>Terms Of Service</h2>
<ol>
<li>Basic Agreement Information
	<ol style="list-style-type: upper-alpha;">
		<li>All amounts are paid by company check or PayPal transfer and mailed to the address you provide to us during the quote process. This usually takes one business day from the date on which your electronical device(s), game(s), console(s), and/or accessories arrive and are inspected at our facility unless we need to speak to you directly about the offer we wish to mak<li>No offer we make is binding upon us until we receive your electronical device(s),  game(s), console(s), and/or accessories and examine them.</li>
		<li>You agree to ship your games within 7 days of receiving the protective packaging and/or prepaid label. If shipping is delayed, the prices we pay may no longer be honored.</li>
		<li>By agreeing to these terms and conditions and by shipping your game(s) to us, you certify that you are the legal owner of the game(s) that you send.</li>
		<li>We strive to make every transaction fast and easy! Should you have any questions regarding these terms and conditions, please do not hesitate to call or email us at info@epictgr.com or use our Contact Us page.</li>
		<li>Updating your information and email communication preferences: We want to communicate with you only if you want to hear from us. If you prefer not to receive information from us, please let us know by sending us an email to info@epictgr.com. Please be sure to include your email address, full name, and specifically what information you do not want to receiv<li>Please note that sometimes these requests may take up to 1-2 weeks to be effectiv<li>In addition, when you sell your games to us online, we may need to contact you via phone, email, or mail to address your questions or issues specific to your order, or with a promotional offer. If you would like to opt out of any further communication followed by completion of the principal transaction(s), please use the opt out link in the email message sent to you or contact us via email including your email address, full name, and specifically what information you do not want to be receiving from us in the futur<li>If you would like to update or correct your Email address, street address, or other personal information with us please contact us either by phone or email.</li>
		<li>Use of EPICTGR.com is intended only for individuals who are at least 13 years ol<li>Individuals under the age of 13 are not eligible to register as Members or use the Services.</li>
	</ol>
</li>

<li>Further Transfer of Ownership and Offer to Purchase
	<ol style="list-style-type: upper-alpha;">
		<li>Prices presented on the websit<li>All such initial prices are pending our evaluation of your electronical device(s), game(s), console(s), and/or accessories and no binding price offer is made until we have had a chance to inspect the electronical device(s) game(s), console(s), and/or accessories that you send to us. We reserve the right to refuse to offer to purchase any item that you send us for any reason we deem, in our sole discretion, to be sensibl<li>You must send us your electronical device(s), game(s), console(s), and/or accessories within the time period stated herein.</li>
		<li>We determine the value of your electronical device (means any electronical device) game (means any video game), console (means any console), and accessory (means any accessory) based on our systematic analysis of the electronical device/game/console/accessory and the current marketplac<li>Many factors are taken into consideration, such as the age of the electronical device/game/console/accessory, the manufacturer and model of the electronical device/game/console/accessory, the wear and tear apparent on the electronical device/game/console/accessory, whether the electronical device</li>/game/console/accessory is usable and or intact in nature and other elements that would affect its resale value or costs of repair to the electronical device/game/console/accessory. If we decide not to purchase the electronical device/game/console/accessory, you will be given the option of allowing us to recycle the electronical device/game/console/accesssory but you will not receive any payment for the electronical device/game/console/accessory. You must appropriately package the electronical device/game/console/accessory you send us in order to protect it from harm during the shipping process. You are solely responsible for any harm that comes to the electronical device/game/console/accessory you send us if you fail to appropriately package the electronical device/game/console/accessory prior to sending it.</li>
		<li>Sending your item to us. You are solely responsible for the risk of loss or damage of/to your property while it is being shipped to us and while it is shipped from us to you, should we return the item to you.</li>
		<li>Should you be given a price via our website AND we, upon inspection of your electronical device/game/console/accessory, agree to pay you that quoted amount, you are legally and contractually bound to sell us the electronical device/game/console/accessory for the price quoted via the website once you have shipped the game/console/accessory to us.</li>
		<li>Should we, upon inspection of your electronical device/game/console/accessory, decide to offer you a lower price than originally quoted, you will have 7 days to either accept or reject that new price quot<li>During the 7 days we will attempt to contact you via phone and/or email several times. If no contact is made after 7 days we will issue payment for amount indicated in the email. Once payment has been issued no revisions or exceptions will be made.</li>
		<li>Lawful Sales Only. You must own the right, title and all legal interest in the electronical device(s), game(s), console(s), and accessories you send us. Your sale and or shipment of any such item must not violate any law, regulation or statute of any jurisdiction. You may not unlawfully transfer or encumber any intellectual property, trademark, copyright, patent, software, license or other legal right or restriction via your shipping or selling of the shipped item. The item you ship must be free of all legal restrictions that would affect the value of the item, restrict your legal right to transfer ownership of the item (including the item itself, software present on the item, or hardware on or inside the item). You must refrain from violating any export laws or restrictions. The item you send (including all related materials) may not be counterfeited, stolen, or contain harmful or offensive content of any natur<li>You agree to hold us harmless and indemnify us from any and all loss of any nature, including fees, costs, judgments, liens and reasonable attorney's fees, arising from any threatened or actual legal action should you violate this term and condition of this Agreement.</li>
		<li>Failure to Return Product or Contents Thereto. Under certain limited circumstances, at no fault of ours, we may not be able to return your item and you agree to hold us harmless from any loss regarding our failure, when outside of our control, to return your electronical device/ game/console/accessory or other item to you.</li>
		<li>Legal title of your electronical device/game/console/accessory passes to us when we agree to pay you the originally quoted amount as shown on our website or you agree to accept a lower offer that we make to you. All payments are sent as established by our normal course of business. If we do not agree to accept your product by way of purchase or as a electronical device/game/console/accessory to be recycled, then title does not pass to us. Title for all electronical device/games/consoles/accessories accepted for recycling passes to us when you agree to allow the game/console/accessory to be recycle<li>All decisions about whether or not we purchase your electronical device/game/console/accessory and for what dollar amount are final. Any offer to purchase your electronical device/game/console/accessory that we make is a non-transferable offer and also expires if not accepted by you in a timely manner, as described herein. At any time we may decide, without prior notice, to discontinue purchasing any particular or all items.</li>
		<li>Errors. Should we make a material error in any representation of facts, information or offers to you, your sole recourse is to request the return of the item that you have sent to us. Your ability to request the return of the item elapses upon your receipt of the payment we issue for your item. In the event that you elect to cancel the transaction prior to receiving our payment, we will return the item to you upon your request.</li>
	</ol>
</li>

	<li>General Terms and Conditions
		<ol style="list-style-type: upper-alpha;">
			<li>Entire Agreement. No Waiver. This Agreement constitutes the entire agreement between the parties. Captions are used only as a matter of convenience and have no legal import. No waiver by us regarding any breach or default shall be deemed to be a waiver of any preceding or subsequent breach or default. Our website or other publications and communications may contain errors. We reserve the right to correct any errors in writing or orally with you.</li>
			<li>Modification. We reserve the right to modify this Agreement at any time without giving you prior notic<li>Your use of our website, any of our tools and services, following any such modification constitutes your agreement to follow and be bound by the Agreement as modifie<li>The last date these Terms of Service were revised is set forth below. Terms and conditions modifying the Agreement are effective immediately upon publication.</li>
		</ol>
	</li>
</ol>

<p>THESE TERMS AND CONDITIONS ARE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH MISSOURI LAW, AND NO CONFLICT OF LAWS OR PROVISIONS OF ANY JURISDICTION WILL APPLY TO THESE TERMS AND CONDITIONS. BY CLICKING ON THE “ACCEPT” BUTTON BELOW, YOU AGREE THAT ANY ACTION AT LAW OR INEQUITY ARISING OUT OF OR RELATING TO THESE TERMS AND CONDITIONS WILL BE FILED ONLY IN STATE OR FEDERAL COURT LOCATED IN RENO, NEVADA AND YOU HEREBY IRREVOCABLY AND UNCONDITIONALLY CONSENT AND SUBMIT TO THE EXCLUSIVE JURISDICTION OF SUCH COURTS OVER ANY SUIT, ACTION, OR PROCEEDING ARISING OUT OF THESE TERMS AND CONDITIONS.</p>
<p>We strive to make every transaction fast and easy! Should you have any questions regarding these terms and conditions, please do not hesitate to email us at info@epictgr.com or use our Contact Us page.</p>
</div>
<?php
require 'includes\part\footer.php';
?>